### ISSUE TITLE
npm install fails on Windows 7 and Windows 8.0

### ISSUE THREAD

**Issue by ajflash** [cscott/node-php-embed#1]
I've tried to install on both platforms with a working Visual Studio 2013 but the install fails. I don't understand the exact causes but I think it is a node-gyp related issue. This is the install script that fails:

**node-pre-gyp install --fallback-to-build**

This is an extract of the console output, if it helps:

```
...
  unpack_libicu_dep
  Extracting C:\Proyectos\Clientes\gpsnode\node_modules\php-embed\deps\icu4c-55_1-src.tgz to C:\Proyectos\Clientes\gpsnode\node_modules\php-embed\build\Release\obj\global_intermediate
  Traceback (most recent call last):
    File "..\..\deps\extract.py", line 15, in <module>
      os.utime(os.path.join(dirname, sys.argv[3]), None) # touch
  WindowsError: [Error 3] El sistema no puede encontrar la ruta especificada: 'C:\\Proyectos\\Clientes\\gpsnode\\node_modules\\php-embed\\build\\Release\\obj\\global_intermediate\\..\\..\\deps\\icu\\source\\configure'
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB6006: "cmd.exe" salió con el código 1. C:\Proyectos\Clientes\gpsnode\node_modules\php-embed\build\deps\libicu_action_before_build.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
...
```

Any help would be apreciated!

**Comment by asifashraf** [comment]
Same issue with me; or similar
Windows 

G:\test\phpembed>npm install php-embed
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path G:\test\phpembed\node_modules\php-embed
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\asif\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=G:\test\phpembed\node_modules\php-embed\lib\binding\node-v93-win32-x64\node_php_embed.node --module_name=node_php_embed --module_path=G:\test\phpembed\node_modules\php-embed\lib\binding\node-v93-win32-x64' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.6.15
npm ERR! node-pre-gyp info using node@16.17.0 | win32 | x64
npm ERR! node-pre-gyp info check checked for "G:\test\phpembed\node_modules\php-embed\lib\binding\node-v93-win32-x64\node_php_embed.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/cscott/node-php-embed/releases/download/0.5.3/node_php_embed-v0.5.3-node-v93-win32-x64.tar.gz
npm ERR! node-pre-gyp http 404 https://github.com/cscott/node-php-embed/releases/download/0.5.3/node_php_embed-v0.5.3-node-v93-win32-x64.tar.gz
npm ERR! node-pre-gyp http Pre-built binary not available for your system, looked for https://github.com/cscott/node-php-embed/releases/download/0.5.3/node_php_embed-v0.5.3-node-v93-win32-x64.tar.gz (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp http Connection closed while downloading tarball file (falling back to source compile with node-gyp)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.17.0 | win32 | x64
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.17.0 | win32 | x64
npm ERR! gyp info ok
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.17.0 | win32 | x64
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.17.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.6 found at "C:\Users\asif\AppData\Local\Programs\Python\Python310\python.exe"
npm ERR! gyp info find Python using Python version 3.10.6 found at "C:\Users\asif\AppData\Local\Programs\Python\Python310\python.exe"
npm ERR! gyp http GET https://nodejs.org/download/release/v16.17.0/node-v16.17.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v16.17.0/node-v16.17.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.17.0/node-v16.17.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.17.0/node-v16.17.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v16.17.0/SHASUMS256.txt
npm ERR! gyp http GET https://nodejs.org/download/release/v16.17.0/win-x86/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v16.17.0/win-x64/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v16.17.0/win-arm64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.17.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.17.0/win-x86/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.17.0/win-x64/node.lib
npm ERR! gyp http 404 https://nodejs.org/download/release/v16.17.0/win-arm64/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v16.17.0/SHASUMS256.txt
npm ERR! gyp http GET https://nodejs.org/download/release/v16.17.0/win-x64/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v16.17.0/win-arm64/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v16.17.0/win-x86/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.17.0/win-x86/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.17.0/SHASUMS256.txt
npm ERR! gyp http 404 https://nodejs.org/download/release/v16.17.0/win-arm64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.17.0/win-x64/node.lib
npm ERR! gyp info find VS using VS2019 (16.11.32802.440) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\asif\AppData\Local\Programs\Python\Python310\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\asif\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'G:\\test\\phpembed\\node_modules\\php-embed\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\asif\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\asif\\AppData\\Local\\node-gyp\\Cache\\16.17.0\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\asif\\AppData\\Local\\node-gyp\\Cache\\16.17.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\asif\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\asif\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.17.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=G:\\test\\phpembed\\node_modules\\php-embed',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'G:\\test\\phpembed\\node_modules\\php-embed\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info find VS using VS2019 (16.11.32802.440) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\asif\AppData\Local\Programs\Python\Python310\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\asif\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'G:\\test\\phpembed\\node_modules\\php-embed\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\asif\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\asif\\AppData\\Local\\node-gyp\\Cache\\16.17.0\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\asif\\AppData\\Local\\node-gyp\\Cache\\16.17.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\asif\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\asif\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.17.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=G:\\test\\phpembed\\node_modules\\php-embed',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'G:\\test\\phpembed\\node_modules\\php-embed\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: C:\Users\asif\AppData\Local\node-gyp\Cache\16.17.0\common.gypi not found (cwd: G:\test\phpembed\node_modules\php-embed) while reading includes of binding.gyp while trying to load binding.gyp
npm ERR! gyp: C:\Users\asif\AppData\Local\node-gyp\Cache\16.17.0\common.gypi not found (cwd: G:\test\phpembed\node_modules\php-embed) while reading includes of binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\asif\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:284:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Windows_NT 10.0.14393
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\asif\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=G:\\test\\phpembed\\node_modules\\php-embed\\lib\\binding\\node-v93-win32-x64\\node_php_embed.node" "--module_name=node_php_embed" "--module_path=G:\\test\\phpembed\\node_modules\\php-embed\\lib\\binding\\node-v93-win32-x64"
npm ERR! gyp ERR! cwd G:\test\phpembed\node_modules\php-embed
npm ERR! gyp ERR! node -v v16.17.0
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\asif\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:284:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Windows_NT 10.0.14393
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\asif\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=G:\\test\\phpembed\\node_modules\\php-embed\\lib\\binding\\node-v93-win32-x64\\node_php_embed.node" "--module_name=node_php_embed" "--module_path=G:\\test\\phpembed\\node_modules\\php-embed\\lib\\binding\\node-v93-win32-x64"
npm ERR! gyp ERR! cwd G:\test\phpembed\node_modules\php-embed
npm ERR! gyp ERR! node -v v16.17.0
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\asif\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=G:\test\phpembed\node_modules\php-embed\lib\binding\node-v93-win32-x64\node_php_embed.node --module_name=node_php_embed --module_path=G:\test\phpembed\node_modules\php-embed\lib\binding\node-v93-win32-x64' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (G:\test\phpembed\node_modules\php-embed\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1093:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.14393
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "G:\\test\\phpembed\\node_modules\\php-embed\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd G:\test\phpembed\node_modules\php-embed
npm ERR! node-pre-gyp ERR! node -v v16.17.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.6.15
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\asif\AppData\Local\npm-cache\_logs\2022-11-05T15_48_16_525Z-debug-0.log
